#!/bin/sh

cd /usr/share/bytebeam/simulator

curl -X GET -H "x-bytebeam-api-key: $BYTEBEAM_API_KEY" -H "X-Bytebeam-tenant: $BYTEBEAM_TENANT" 'https://cloud.bytebeam.io/api/v1/devices/1/cert' > $CONFIG_FILE

exec simulator
